name = "UnitfulData"
uuid = "479269fd-87c4-43d6-a395-02aad47d928b"
authors = ["Marco Menarini"]
version = "0.6.3"

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Unitful = "1.21"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
